export const ENTER = 'Enter'
export const DESTROY = 'destroy'
export const TOGGLE = 'toggle'
export const ACTIVE = 'active'
export const COMPLETED = 'completed'
export const ALLSELECTED = 'all selected'
export const INIT = 'init'
